#include "clipboard_bridge.h"
#include "native_server.h"

#include <QByteArrayView>
#include <QClipboard>
#include <QCryptographicHash>
#include <QDebug>
#include <QGuiApplication>
#include <QHash>
#include <QMap>
#include <QMimeData>
#include <QPointer>
#include <QSet>
#include <QSocketNotifier>
#include <QTimer>
#include <QtEndian>

#include <algorithm>
#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <functional>
#include <pthread.h>
#include <signal.h>
#include <unistd.h>
#include <utility>
#include <vector>

namespace {
using Payloads = QMap<QByteArray, QByteArray>;

struct Selection {
    Payloads payloads;
    QByteArray fingerprint;
};

QByteArray fingerprint(const Payloads &payloads)
{
    QCryptographicHash hash(QCryptographicHash::Sha256);
    for (auto it = payloads.cbegin(); it != payloads.cend(); ++it) {
        hash.addData(it.key());
        hash.addData(QByteArrayView("\0", 1));
        const quint64 length = qToBigEndian(quint64(it.value().size()));
        hash.addData(QByteArrayView(reinterpret_cast<const char *>(&length), sizeof(length)));
        hash.addData(it.value());
    }
    return hash.result();
}

bool mimeBytes(const QString &name, QByteArray &bytes)
{
    bytes = name.toLatin1();
    if (bytes.isEmpty() || bytes.contains('\0') || QString::fromLatin1(bytes) != name) {
        qWarning() << "Clipboard: cannot transport invalid MIME name" << name;
        return false;
    }
    return true;
}

bool prepareFd(int fd)
{
    const int flags = fcntl(fd, F_GETFL);
    if (flags < 0 || fcntl(fd, F_SETFL, flags | O_NONBLOCK) < 0)
        return false;
    const int descriptorFlags = fcntl(fd, F_GETFD);
    return descriptorFlags >= 0 && fcntl(fd, F_SETFD, descriptorFlags | FD_CLOEXEC) >= 0;
}

// A departed Wayland recipient must not terminate the GUI with SIGPIPE. Mask
// only this thread and consume only a signal generated by this write, preserving
// both the process's signal disposition and any previously pending SIGPIPE.
ssize_t writeWithoutSigpipe(int fd, const void *data, size_t size)
{
    sigset_t blocked, previous, pending;
    sigemptyset(&blocked);
    sigaddset(&blocked, SIGPIPE);
    const int error = pthread_sigmask(SIG_BLOCK, &blocked, &previous);
    if (error != 0) {
        errno = error;
        return -1;
    }
    if (sigpending(&pending) != 0) {
        const int saved = errno;
        pthread_sigmask(SIG_SETMASK, &previous, nullptr);
        errno = saved;
        return -1;
    }
    const bool alreadyPending = sigismember(&pending, SIGPIPE) == 1;
    const ssize_t result = ::write(fd, data, size);
    const int saved = errno;
    if (result < 0 && saved == EPIPE && !alreadyPending) {
        const timespec noWait{};
        while (sigtimedwait(&blocked, nullptr, &noWait) < 0 && errno == EINTR) {}
    }
    pthread_sigmask(SIG_SETMASK, &previous, nullptr);
    errno = saved;
    return result;
}

class Transfer final : public QObject {
public:
    using Completion = std::function<void(bool, QByteArray)>;

    Transfer(int fd, bool writing, QByteArray bytes,
             std::shared_ptr<const Selection> selection, Completion complete, QObject *parent)
        : QObject(parent), m_fd(fd), m_writing(writing), m_bytes(std::move(bytes)),
          m_selection(std::move(selection)), m_complete(std::move(complete)),
          m_notifier(new QSocketNotifier(fd, writing ? QSocketNotifier::Write : QSocketNotifier::Read, this)),
          m_timeout(new QTimer(this))
    {
        m_timeout->setSingleShot(true);
        m_timeout->setInterval(15000);
        connect(m_timeout, &QTimer::timeout, this, [this] {
            qWarning() << "Clipboard:" << (m_writing ? "send" : "receive") << "timed out";
            finish(false);
        });
        connect(m_notifier, &QSocketNotifier::activated, this, [this] { ready(); });
        m_timeout->start();
        QTimer::singleShot(0, this, [this] { ready(); });
    }

    ~Transfer() override
    {
        m_notifier->setEnabled(false);
        if (m_fd >= 0)
            ::close(m_fd);
    }

private:
    void finish(bool success)
    {
        if (m_fd < 0)
            return;
        m_notifier->setEnabled(false);
        m_timeout->stop();
        ::close(std::exchange(m_fd, -1));
        auto complete = std::move(m_complete);
        deleteLater();
        if (complete)
            complete(success, std::move(m_bytes));
    }

    void ready()
    {
        if (m_fd < 0)
            return;
        // Bound each event-loop turn, not payload size. Large selections remain
        // asynchronous and may make progress for as long as their peer does.
        constexpr qsizetype chunkSize = 64 * 1024;
        constexpr qsizetype turnLimit = 256 * 1024;
        qsizetype progressed = 0;
        char chunk[chunkSize];
        while (progressed < turnLimit) {
            if (m_writing && m_offset == m_bytes.size()) {
                finish(true);
                return;
            }
            const ssize_t count = m_writing
                ? writeWithoutSigpipe(m_fd, m_bytes.constData() + m_offset,
                                      size_t(std::min(chunkSize, m_bytes.size() - m_offset)))
                : ::read(m_fd, chunk, sizeof(chunk));
            if (count > 0) {
                if (m_writing)
                    m_offset += count;
                else
                    m_bytes.append(chunk, qsizetype(count));
                progressed += count;
                m_timeout->start();
                continue;
            }
            if (count == 0) {
                finish(!m_writing);
                return;
            }
            if (errno == EINTR)
                continue;
            if (errno == EAGAIN || errno == EWOULDBLOCK)
                return;
            qWarning() << "Clipboard:" << (m_writing ? "send" : "receive")
                       << "failed:" << std::strerror(errno);
            finish(false);
            return;
        }
    }

    int m_fd;
    bool m_writing;
    QByteArray m_bytes;
    std::shared_ptr<const Selection> m_selection;
    Completion m_complete;
    QSocketNotifier *m_notifier;
    QTimer *m_timeout;
    qsizetype m_offset = 0;
};
} // namespace

class ClipboardBridge::Private final : public QObject {
public:
    Private(cm_server *server, ClipboardBridge *parent)
        : QObject(parent), server(server), clipboard(QGuiApplication::clipboard())
    {
        connect(clipboard, &QClipboard::dataChanged, this, [this] { hostChanged(); });
        connect(qGuiApp, &QGuiApplication::applicationStateChanged, this,
                [this](Qt::ApplicationState state) {
            if (state == Qt::ApplicationActive)
                refresh();
        });
        QTimer::singleShot(0, this, [this] { refresh(); });
    }

    void cancelIncoming()
    {
        delete std::exchange(reader, nullptr);
        incoming.reset();
    }

    bool isExportedClipboard() const
    {
        return exported && clipboard->mimeData(QClipboard::Clipboard) == exported.data();
    }

    void hostChanged()
    {
        if (isExportedClipboard())
            return;
        const quint64 current = ++revision;
        cancelIncoming();
        // Qt may emit dataChanged during Wayland dispatch. Retrieve the host's
        // MIME data outside that signal stack, and let newer events supersede it.
        QTimer::singleShot(0, this, [this, current] {
            if (current == revision)
                offerHost(current);
        });
    }

    void refresh()
    {
        // Focus activation can occur between receipt and EOF of a nested copy.
        // Re-offering the old desktop clipboard here would destroy its source.
        if (incoming || isExportedClipboard())
            return;
        offerHost(revision);
    }

    void offerHost(quint64 current)
    {
        if (!server || incoming || current != revision)
            return;
        const QMimeData *mime = clipboard->mimeData(QClipboard::Clipboard);
        QPointer<const QMimeData> guardedMime(mime);
        auto snapshot = std::make_shared<Selection>();
        const QStringList formats = mime ? mime->formats() : QStringList{};
        for (const QString &format : formats) {
            if (!guardedMime || current != revision)
                return;
            QByteArray name;
            if (!mimeBytes(format, name))
                return;
            const QByteArray bytes = guardedMime->data(format);
            if (!guardedMime || current != revision)
                return;
            // QByteArray::fromRawData is legal in a QMimeData subclass: do not
            // retain even implicitly shared bytes borrowed from that object.
            snapshot->payloads.insert(name, QByteArray(bytes.constData(), bytes.size()));
        }
        if (current != revision)
            return;
        if (snapshot->payloads.isEmpty())
            snapshot->payloads.insert(QByteArrayLiteral("text/plain"), QByteArray{});
        snapshot->fingerprint = fingerprint(snapshot->payloads);
        if (nestedOwnsSelection && nestedGeneration == exportedGeneration
            && clipboard->ownsClipboard() && snapshot->fingerprint == exportedFingerprint)
            return;
        const auto active = offered.constFind(activeToken);
        if (!nestedOwnsSelection && active != offered.cend()
            && (*active)->fingerprint == snapshot->fingerprint)
            return;

        do {
            ++nextToken;
        } while (nextToken == 0 || offered.contains(nextToken));
        const quint64 token = nextToken;
        offered.insert(token, snapshot);
        activeToken = token;
        nestedOwnsSelection = false;
        std::vector<const char *> names;
        names.reserve(size_t(snapshot->payloads.size()));
        for (auto it = snapshot->payloads.cbegin(); it != snapshot->payloads.cend(); ++it)
            names.push_back(it.key().constData());
        // The native source may synchronously release the previous token.
        cm_server_offer_selection(server, names.data(), names.size(), token);
    }

    void nestedSelection(quint64 generation, const QStringList &formats)
    {
        const quint64 current = ++revision;
        cancelIncoming();
        nestedOwnsSelection = true;
        nestedGeneration = generation;
        incoming = std::make_unique<Incoming>();
        incoming->generation = generation;
        incoming->revision = current;
        QSet<QByteArray> seen;
        for (const QString &format : formats) {
            QByteArray name;
            if (!mimeBytes(format, name)) {
                cancelIncoming();
                return;
            }
            if (!seen.contains(name)) {
                seen.insert(name);
                incoming->formats.push_back(std::move(name));
            }
        }
        receiveNext();
    }

    void receiveNext()
    {
        if (!incoming)
            return;
        if (incoming->next == incoming->formats.size()) {
            publishIncoming();
            return;
        }
        int pipeFds[2];
        if (pipe2(pipeFds, O_CLOEXEC) != 0) {
            qWarning() << "Clipboard: cannot create receive pipe:" << std::strerror(errno);
            cancelIncoming();
            return;
        }
        // Only our read end is nonblocking. The client's source implementation
        // decides how to schedule writes to the descriptor it receives.
        if (!prepareFd(pipeFds[0])) {
            qWarning() << "Clipboard: cannot prepare receive descriptor:" << std::strerror(errno);
            ::close(pipeFds[0]);
            ::close(pipeFds[1]);
            cancelIncoming();
            return;
        }
        const quint64 current = incoming->revision;
        const quint64 generation = incoming->generation;
        const QByteArray name = incoming->formats[incoming->next];
        reader = new Transfer(pipeFds[0], false, {}, {},
            [this, current, name](bool success, QByteArray bytes) {
                if (!incoming || incoming->revision != current)
                    return;
                reader = nullptr;
                if (!success) {
                    incoming.reset();
                    return;
                }
                incoming->payloads.insert(name, std::move(bytes));
                ++incoming->next;
                receiveNext();
            }, this);
        // The C boundary consumes the write end even for an obsolete source.
        if (!cm_server_receive_selection(server, generation, name.constData(), pipeFds[1])) {
            qWarning() << "Clipboard: nested selection expired before receiving" << name;
            if (incoming && incoming->revision == current)
                cancelIncoming();
        }
    }

    void publishIncoming()
    {
        auto complete = std::move(incoming);
        if (complete->revision != revision)
            return;
        if (complete->payloads.isEmpty())
            complete->payloads.insert(QByteArrayLiteral("text/plain"), QByteArray{});
        auto *mime = new QMimeData;
        for (auto it = complete->payloads.cbegin(); it != complete->payloads.cend(); ++it)
            mime->setData(QString::fromLatin1(it.key()), it.value());
        exportedFingerprint = fingerprint(complete->payloads);
        exportedGeneration = complete->generation;
        exported = mime;
        clipboard->setMimeData(mime, QClipboard::Clipboard);
    }

    void sendSelection(quint64 token, const QString &mime, int fd)
    {
        if (fd < 0) {
            qWarning() << "Clipboard: source received an invalid send descriptor";
            return;
        }
        QByteArray name;
        const auto source = offered.constFind(token);
        if (!mimeBytes(mime, name) || source == offered.cend()) {
            qWarning() << "Clipboard: send requested for an unavailable selection" << token;
            ::close(fd);
            return;
        }
        const auto payload = (*source)->payloads.constFind(name);
        if (payload == (*source)->payloads.cend()) {
            qWarning() << "Clipboard: send requested an unoffered MIME type" << mime;
            ::close(fd);
            return;
        }
        if (!prepareFd(fd)) {
            qWarning() << "Clipboard: cannot prepare send descriptor:" << std::strerror(errno);
            ::close(fd);
            return;
        }
        // Each active writer retains its immutable generation even after a
        // replacement source causes releaseSelection(token).
        new Transfer(fd, true, *payload, *source, {}, this);
    }

    void releaseSelection(quint64 token)
    {
        offered.remove(token);
        if (activeToken == token)
            activeToken = 0;
    }

private:
    struct Incoming {
        quint64 generation = 0;
        quint64 revision = 0;
        std::vector<QByteArray> formats;
        size_t next = 0;
        Payloads payloads;
    };

    cm_server *server;
    QClipboard *clipboard;
    QHash<quint64, std::shared_ptr<const Selection>> offered;
    std::unique_ptr<Incoming> incoming;
    Transfer *reader = nullptr;
    QPointer<QMimeData> exported;
    QByteArray exportedFingerprint;
    quint64 revision = 0;
    quint64 nextToken = 0;
    quint64 activeToken = 0;
    quint64 nestedGeneration = 0;
    quint64 exportedGeneration = 0;
    bool nestedOwnsSelection = false;
};

ClipboardBridge::ClipboardBridge(cm_server *server, QObject *parent)
    : QObject(parent), d(std::make_unique<Private>(server, this))
{
}

ClipboardBridge::~ClipboardBridge() = default;

void ClipboardBridge::nestedSelection(quint64 generation, const QStringList &formats)
{
    d->nestedSelection(generation, formats);
}

void ClipboardBridge::sendSelection(quint64 token, const QString &mime, int fd)
{
    d->sendSelection(token, mime, fd);
}

void ClipboardBridge::releaseSelection(quint64 token)
{
    d->releaseSelection(token);
}

void ClipboardBridge::refresh()
{
    d->refresh();
}
